"""Soft reminders for broad mutation and drift-prone tool actions."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Mapping

from agent.tool_result_classification import FILE_MUTATING_TOOL_NAMES
from utils import safe_json_loads


BROAD_ACTION_WRITE_THRESHOLD = 3
BROAD_ACTION_PATH_THRESHOLD = 8

WRITE_CAPABLE_TOOL_NAMES = frozenset(
    {
        "terminal",
        "execute_code",
        "write_file",
        "patch",
    }
)

GENERATED_PATH_SEGMENTS = frozenset(
    {
        "dist",
        "build",
        "coverage",
        ".next",
        ".nuxt",
        "node_modules",
        "__pycache__",
        ".pytest_cache",
        "target",
        "out",
    }
)

GENERATED_FILE_MARKERS = (
    "generated",
    "auto-generated",
    "autogenerated",
    ".min.js",
    ".bundle.js",
    ".lock",
)

MEDIA_OUTPUT_EXTENSIONS = frozenset(
    {
        ".mp3",
        ".mp4",
        ".mov",
        ".wav",
        ".webm",
        ".png",
        ".jpg",
        ".jpeg",
        ".gif",
        ".webp",
    }
)

EDITOR_BACKUP_SUFFIXES = (
    "~",
    ".bak",
    ".backup",
    ".orig",
    ".tmp",
    ".swp",
    ".swo",
)

PACKAGE_MANAGER_RE = re.compile(r"(?<![\w.-])(?P<pm>npm|yarn)\s+(?P<cmd>install|i|add|remove|rm|run|exec|dlx|create)\b")
PATH_TOKEN_RE = re.compile(r"(?<![\w.-])(?:[A-Za-z]:[\\/][^\s\"'`<>|]+|[/~.]?[A-Za-z0-9_.-]+(?:[\\/][A-Za-z0-9_.-]+)+)")


@dataclass
class BroadActionReminderState:
    """Per-turn facts used to render low-noise broad-action reminders."""

    write_actions: int = 0
    paths: set[str] = field(default_factory=set)
    generated_paths: set[str] = field(default_factory=set)
    package_manager_nudges: set[str] = field(default_factory=set)
    reminder_emitted: bool = False


def observe_tool_call(
    state: BroadActionReminderState,
    tool_name: str,
    args: Mapping[str, Any] | None,
    result: Any = None,
) -> None:
    """Update reminder state after a non-blocked tool call."""

    if not isinstance(state, BroadActionReminderState):
        return
    if tool_name not in WRITE_CAPABLE_TOOL_NAMES:
        return

    state.write_actions += 1
    paths = _extract_paths(tool_name, args or {}, result)
    state.paths.update(paths)
    for path in paths:
        if is_drift_prone_artifact_path(path):
            state.generated_paths.add(path)

    if tool_name in {"terminal", "execute_code"}:
        text = _command_text(args or {})
        for pm in package_manager_nudges(text, cwd=_cwd_from_args(args or {})):
            state.package_manager_nudges.add(pm)


def format_broad_action_reminder(state: BroadActionReminderState | None) -> str:
    """Render a user-visible advisory, or ``""`` when the turn should stay quiet."""

    if state is None:
        return ""

    triggered = (
        state.write_actions >= BROAD_ACTION_WRITE_THRESHOLD
        or len(state.paths) >= BROAD_ACTION_PATH_THRESHOLD
        or bool(state.generated_paths)
        or bool(state.package_manager_nudges)
    )
    if not triggered:
        return ""

    lines = ["Action-scope reminder:"]

    if state.write_actions >= BROAD_ACTION_WRITE_THRESHOLD or len(state.paths) >= BROAD_ACTION_PATH_THRESHOLD:
        detail = f"{state.write_actions} write-capable tool action(s)"
        if state.paths:
            detail += f" touching {len(state.paths)} path(s)"
        lines.append(
            f"- Broad edit volume detected ({detail}). Check the requested scope, inspect dirty state, "
            "and route broad implementation to worker dispatch, Kanban, or coding agents instead of "
            "continuing large implementation inside the orchestrator context."
        )

    if state.generated_paths:
        sample = ", ".join(f"`{path}`" for path in sorted(state.generated_paths)[:6])
        more = len(state.generated_paths) - 6
        if more > 0:
            sample += f", and {more} more"
        lines.append(
            "- Drift-prone generated/runtime artifact path(s) appeared: "
            f"{sample}. Avoid treating build output, caches, local media outputs, generated files, "
            "or editor backups as durable source unless the repo explicitly owns them."
        )

    if state.package_manager_nudges:
        pms = ", ".join(sorted(state.package_manager_nudges))
        lines.append(
            f"- Package-manager drift nudge: `{pms}` appeared. Prefer `pnpm` or `bun`; use `npm` "
            "or `yarn` only when repo evidence or the user instruction supports that choice."
        )

    lines.append("This is a reminder, not a block.")
    return "\n".join(lines)


def pop_broad_action_reminder(state: BroadActionReminderState | None) -> str:
    """Return the first reminder for a turn and mark it emitted."""

    if state is None or state.reminder_emitted:
        return ""
    reminder = format_broad_action_reminder(state)
    if reminder:
        state.reminder_emitted = True
    return reminder


def is_drift_prone_artifact_path(path: str) -> bool:
    normalized = _normalize_path(path)
    if not normalized:
        return False

    lowered = normalized.lower()
    segments = [segment for segment in re.split(r"[/\\]+", lowered) if segment and segment != "."]
    if any(segment in GENERATED_PATH_SEGMENTS for segment in segments):
        return True
    if any(marker in lowered for marker in GENERATED_FILE_MARKERS):
        return True
    if lowered.endswith(EDITOR_BACKUP_SUFFIXES):
        return True

    suffix = Path(lowered).suffix
    if suffix in MEDIA_OUTPUT_EXTENSIONS and any(segment in {"output", "outputs", "renders", "media"} for segment in segments):
        return True

    return False


def package_manager_nudges(command_text: str, *, cwd: str | None = None) -> set[str]:
    """Return npm/yarn names that need a soft preference reminder."""

    nudges: set[str] = set()
    if not command_text:
        return nudges

    for match in PACKAGE_MANAGER_RE.finditer(command_text):
        pm = match.group("pm")
        if _package_manager_supported(pm, cwd):
            continue
        nudges.add(pm)
    return nudges


def _extract_paths(tool_name: str, args: Mapping[str, Any], result: Any) -> set[str]:
    paths: set[str] = set()

    if tool_name in FILE_MUTATING_TOOL_NAMES:
        try:
            from agent.tool_dispatch_helpers import (
                _extract_file_mutation_targets,
                _extract_landed_file_mutation_paths,
            )

            paths.update(_extract_file_mutation_targets(tool_name, dict(args)))
            paths.update(_extract_landed_file_mutation_paths(tool_name, dict(args), result))
        except Exception:
            pass

    if tool_name in {"terminal", "execute_code"}:
        for token in PATH_TOKEN_RE.findall(_command_text(args)):
            paths.add(token)

    return {path for path in (_normalize_path(path) for path in paths) if path}


def _command_text(args: Mapping[str, Any]) -> str:
    for key in ("command", "code", "script"):
        value = args.get(key)
        if isinstance(value, str):
            return value
    return ""


def _cwd_from_args(args: Mapping[str, Any]) -> str | None:
    for key in ("cwd", "workdir", "working_dir"):
        value = args.get(key)
        if isinstance(value, str) and value.strip():
            return value
    return None


def _package_manager_supported(pm: str, cwd: str | None) -> bool:
    if not cwd:
        cwd = "."
    try:
        root = Path(cwd).expanduser()
        if not root.exists() or not root.is_dir():
            return False
    except Exception:
        return False

    if pm == "npm" and (root / "package-lock.json").exists():
        return True
    if pm == "yarn" and ((root / "yarn.lock").exists() or (root / ".yarnrc.yml").exists()):
        return True

    try:
        package_json = safe_json_loads((root / "package.json").read_text(encoding="utf-8"))
    except Exception:
        package_json = None
    if isinstance(package_json, dict):
        package_manager = str(package_json.get("packageManager") or "").lower()
        if package_manager.startswith(f"{pm}@"):
            return True

    return False


def _normalize_path(path: str) -> str:
    if not isinstance(path, str):
        return ""
    path = path.strip().strip("\"'")
    if not path:
        return ""
    return path.replace("\\", "/")
